apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dc-python-app-b
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/igabi/dc-python-app-b
spec:
  destination:
    namespace: dc-python-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dc-python-app-b
    repoURL: https://igabi@github.com/igabi/dc-helmchart.git
    targetRevision: HEAD 
  syncPolicy:
    automated: {}
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
